watch_stylesheet: true
watch_config: true
debug: false
update_check: true
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 5
      left: 5
      bottom: 0
      right: 5
    widgets:
      left:
      - "glazewm_workspaces"
      - "active_window"
      center:
      - "weather"
      - "clock"
      right:
      - "wifi"
      - "volume"
      - "glazewm_tiling_direction"
      - "language_menu"
      - "battery"
      - "notifications"
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M %p}"
      locale: ""
      update_interval: 1000
      timezones: []
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_holidays: false
        show_week_numbers: false
        country_code: "TH"
        holiday_color: "#FF6464"
        extended: false
      callbacks:
        on_left: "toggle_calendar"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      show_alerts: true
      tooltip: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "Samut Prakan, TH" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyDay: "\ue30a"
        snowyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "12h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line
        current_line_color: "#8EAEE8"
        current_line_width: 1 # can be 0 to hide the current hour line
        current_line_style: "dot"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "\udb80\udcad"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: true
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      animation: true

  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 34
      max_length_ellipsis: "..."
      monitor_exclusive: true
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "\uf476  {count}"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon} {percent}%"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 30
        medium: 60
        high: 90
        full: 100
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\udb80\udc7a"
        icon_low: "\udb80\udc7b"
        icon_medium: "\udb80\udc7e"
        icon_high: "\udb80\udc81"
        icon_full: "\udb80\udc79"
  language_menu:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[country_code]}"
      update_interval: 1
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon}  {wifi_strength}%"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "{wifi_icon}  ETH"
      ethernet_label_alt: "{wifi_icon} {ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: true  # Optional. Will require location access permission if true.
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-24% strength
        "\udb82\udd22",  # Icon for 25-49% strength
        "\udb82\udd25",  # Icon for 50-74% strength
        "\udb82\udd28"   # Icon for 75-100% strength
      ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: [
          "\ue670",
          "\ue671",
          "\ue672",
          "\ue673",
        ]
        wifi_icons_unsecured: [
          "\uec3c",
          "\uec3d",
          "\uec3e",
          "\uec3f",
        ]